import { BeerClub } from "~/server/Beer.js";

export const beerClubs: { [key: number]: BeerClub } = {
  7: {
    name: "Round 7",
    date: new Date("2024-11-08"),
    beers: [
      {
        url: "https://www.kihoskh.dk/collections/christmas-beers/products/brouwerij-corsendonk-corsendonk-christmas-ale",
        name: "Corsendonk Christmas Ale",
        brewery: "Corsendonk",
        summary: "This typical deep red-brown end-of-year beer was made from roasted special malts, the finest hops and selected yeasts and seasoned with a hint of coriander. Corsendonk Christmas gives the best of what a Christmas beer can give, a round balanced taste with a dry and refined adonk.",
        image: "/img/club/7/Corsendonk_Christmas_k.png.webp",
        abv: 8.1,
        country: "Belgium 🇧🇪",
        type: "Belgian Winter Ale",
        volume: "33 CL",
      },

      {
        url: "https://www.kihoskh.dk/collections/sours/products/bianca-non-alcoholic-raspberry-peach-marshmallow-lassi-gose",
        name: "Bianca Non-Alcoholic Raspberry Peach Marshmallow Lassi Gose",
        brewery: "Omnipollo",
        summary: "Explore the bold flavors of Bianca Non-Alcoholic Raspberry Peach Marshmallow Lassi Gose by Omnipollo, a refreshing Sour beer with just 0.3% ABV. This unique version remains true to the iconic Bianca series with its globally-sourced fruit notes. Experience the distinctive taste of Bianca without the usual alcohol content, perfect for any occasion. Its vibrant beetroot-like appearance is sure to catch attention, while the combination of marshmallows, peaches, and raspberries creates a well-balanced flavor. The addition of salt provides the final touch, making Bianca Non-Alcoholic Raspberry Peach Marshmallow Lassi Gose a must-try for any beer enthusiast.",
        image: "/img/club/7/Omnipolloo_BiancaNonAlcoStrawberryPeachMarshmallow_k.png.webp",
        abv: 0.3,
        country: "Sweden 🇸🇪",
        type: "Non Alcoholic Sour",
        volume: "33 CL",
      },
      {
        url: "https://www.kihoskh.dk/products/freak-wave-ipa",
        name: "Freak Wave IPA",
        brewery: "Gamma Brewing",
        summary: "Gamma's Freak Wave IPA, featuring a blend of Cashmere, Mosaic, and Citra hops, with Pilsner, Oat, and Carapils malts, is fermented with WLP066 yeast, resulting in a complex flavor profile with a crisp, light finish. An ideal choice for those searching for a reliable Hop Juice hit. A well-balanced and refreshing beer that packs citrus and stone fruit flavors. Perfect for hop heads and casual drinkers alike.",
        image: "/img/club/7/Gamma_FreakWave_k_0fedb90f-c567-4691-8a41-bcd343fdbd67.png.webp",
        abv: 6.5,
        country: "Denmark 🇩🇰",
        type: "IPA",
        volume: "44 CL",
      },

      {
        url: "https://www.kihoskh.dk/products/donut-series-2-0-boston-cream-custard-filing-with-toffee-drizzle-pastry-stout",
        name: "Donut Series 2.0 Boston Cream Custard Filing With Toffee Drizzle Pastry Stout",
        brewery: "Amundsen Brewery",
        summary: 'Elevate your taste experience with the "DONUT SERIES 2.0 Boston Cream Custard Filling with Toffee Drizzle." This imperial pastry stout, boasting an impressive 11.5% ABV, is a triumph of flavor and creativity from Amundsen Brewery. Indulge in the velvety richness of boston cream custard filling, skillfully infused with the allure of toffee drizzle. With each sip, you\'ll be transported to a world of delectable confections, where layers of flavor intertwine in harmonious delight.',
        image: "/img/club/7/Amundsen_Donut-Boston_k.png.webp",
        abv: 11.5,
        country: "Norway 🇳🇴",
        type: "Pastry Stout",
        volume: "44 CL",
      },
      {
        url: "https://www.kihoskh.dk/collections/pale-ale/products/fort-point-pale-ale",
        name: "Fort Point Pale Ale",
        brewery: "Trillium Brewing Company",
        summary: "Fort Point Pale Ale is a top choice for the discerning beer drinker. Its light, crisp malt character is enhanced by an abundance of hop aromatics and flavors from Citra and Columbus. The fragrant nose boasts fresh citrus, tropical fruit, and peach notes while bold flavors of pineapple and mango mingle with dank hints of zesty citrus and fresh pine needles. This American pale ale also offers a smooth mouthfeel, mild bitterness, and dry finish, making it the perfect daily-drinking option. And with a 6.6% alcohol content, it's a great choice for any occasion.",
        image: "/img/club/7/Trillium_FortPoint_k.png.webp",
        abv: 6.6,
        country: "USA 🇺🇸",
        type: "Pale Ale",
        volume: "44 CL",
      },
      {
        url: "https://www.kihoskh.dk/collections/christmas-beers/products/risalamande-danish-rice-pudding-sour-x-vaeskebalancen",
        name: "Risalamande ‘Danish Rice Pudding’ Sour",
        brewery: "Vault City Brewing X Væskebalancen",
        summary: "Experience the rich and tangy flavors of Vault City's newest dessert sour inspired by traditional Danish Rice Pudding. This expertly crafted, mixed fermentation beer features the perfect blend of sweet cherries, smooth vanilla, and flaked rice, with subtle hints of almond. Collaboratively made with Denmark's Væskebalancen, this 6% ABV seasonal delicacy is a must-try for beer enthusiasts. Don't miss out on this one-of-a-kind, deliciously unique sour beer.",
        image: "/img/club/7/VaultCity_Risalamande_k.png.webp",
        abv: 6,
        country: "Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿 x Denmark 🇩🇰",
        type: "Pastry Sour",
        volume: "44 CL",
      },
      {
        url: "https://www.kihoskh.dk/collections/ipas-dipa-more/products/spikes-west-coast-ipa",
        name: "Spikes West Coast IPA",
        brewery: "Põhjala x Garage Beer Co.",
        summary: "Discover the ultimate taste of the West Coast with Spikes West Coast IPA, a joint effort from Põhjala and Garage Beer Co. This refined brew showcases a potent combination of Nelson Sauvin, Citra, and HBC 522 hops, meticulously brewed for a perfectly balanced and invigorating beer. With a 6.4% alcohol content, this IPA offers a distinct West Coast experience, thanks to its sharp bitterness and rich amber hue.",
        image: "/img/club/7/Pohjala_Spike_k_f085a0f6-5140-4840-9c2b-26ea1d3dab44.png.webp",
        abv: 6.4,
        country: "Estonia 🇪🇪 x USA 🇺🇸",
        type: "West Coast IPA",
        volume: "44 CL",
      },
      {
        url: "https://www.kihoskh.dk/collections/sale/products/back-to-black-oloroso-barrel-aged-stout",
        name: "Back to Black Oloroso Barrel Aged Stout",
        brewery: "Cierzo",
        summary: "Experience the rich complexity of our beloved classic, Back To Black, now aged in Oloroso barrels. The original coffee and cocoa notes blend with the liquorice flavors of Chinook hops, enhanced by the depth and nuances of this exceptional Jerez wine.",
        image: "/img/club/7/Cierzo_BacktoBlack.png.webp",
        abv: 9,
        country: "Spain 🇪🇸",
        type: "Imperial Stout",
        volume: "75 CL",
      },
    ],
  },
};
